//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiegleSalary.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AiegleSalaryEntities : DbContext
    {
        public AiegleSalaryEntities()
            : base("name=AiegleSalaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_BasicWP> T_BasicWP { get; set; }
        public virtual DbSet<T_Emp> T_Emp { get; set; }
        public virtual DbSet<T_EmpSalary> T_EmpSalary { get; set; }
        public virtual DbSet<T_FlowType> T_FlowType { get; set; }
        public virtual DbSet<T_WPCard> T_WPCard { get; set; }
    }
}
