//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiegleSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BasicWP
    {
        public string WPCode { get; set; }
        public string GongXu { get; set; }
        public string GXContent { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Price { get; set; }
        public string ReMark { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> CountDefaultValue { get; set; }
        public int ID { get; set; }
    }
}
