//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiegleSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EmpSalary
    {
        public int ID { get; set; }
        public string OrderID { get; set; }
        public string WPCode { get; set; }
        public string EID { get; set; }
        public string EName { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Memo { get; set; }
        public Nullable<int> ListType { get; set; }
    }
}
