//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiegleSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Emp
    {
        public string EID { get; set; }
        public string FID { get; set; }
        public string EmpName { get; set; }
        public string Dept { get; set; }
        public string POS { get; set; }
        public Nullable<double> CheckRate { get; set; }
        public int ID { get; set; }
    }
}
