//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiegleSalary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WPCard
    {
        public int ID { get; set; }
        public string DealerName { get; set; }
        public string OrderID { get; set; }
        public string OrderDate { get; set; }
        public string TotalArea { get; set; }
        public string MArea { get; set; }
        public string BArea { get; set; }
        public Nullable<System.DateTime> APDate { get; set; }
        public string wpCode { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> PricePer { get; set; }
        public int AppStatus { get; set; }
        public string AppBy { get; set; }
        public Nullable<int> ListType { get; set; }
        public string A1 { get; set; }
        public string A2 { get; set; }
        public string A3 { get; set; }
        public string A4 { get; set; }
        public string A5 { get; set; }
        public Nullable<int> MQty { get; set; }
    }
}
